name: iceb
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  font_awesome_flutter:
  flutter_gen: any
  get: ^4.6.6
  equatable:
  json_annotation: ^4.8.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.1
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  animate_do: ^3.3.4


dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/onboarding/

  fonts:
    - family: chiralla
      fonts:
        - asset: fonts/chiralla/chiralla.ttf
          style: normal
    - family: nova_klasse
      fonts:
        - asset: fonts/novaklasse/novaklasse_semibold.otf
          style: normal
        - asset: fonts/novaklasse/novaklasse_semibdoblique.otf
          style: italic



